#Import Libraries

In [60]:
import pandas as pd

#Extract

The file our client is able to download is an Excel file with merged cells, and every order is in a different table with all GLN, address, qty, etc info. It's easy to read in Excel but it's not so easy to read to create our dataframe so, we'll need to transform the file into a dataframe we can use here

In [61]:
orders = pd.read_csv('Order_Example.csv')
orders = orders.T.reset_index(drop=True).T

In [62]:
orders.head(20)

,0,1,2,3,4,5,6,7,8,9,...,19,20,21,22,23,24,25,26,27,28
0,Buyer:,NaN,NaN,DESIGNER LIVING CO,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,Seller:,NaN,Luxury Furniture Group,NaN,NaN,NaN
1,GB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,(011223344)\n17 Zaba Tower\nLondon\nNN9 7FR\nGB,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Order Information,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,Order No:,NaN,NaN,0050920111,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,Order Date:,NaN,NaN,NaN,17/08/2023,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Line,NaN,Seller Code,NaN,NaN,NaN,Barcode,Buyer Code,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Packing,NaN,Quantity,Unit Price,Value
15,NaN,NaN,OAKWOOD DINIG TABLE,NaN,NaN,NaN,1012223334445,012345678,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1,NaN,2.,120.00,240.00
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Total Qty:,NaN,2,Total Value:,240.00
17,EDI Ref: 1702,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Buyer:,NaN,NaN,DESIGNER LIVING CO,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,Seller:,NaN,Luxury Furniture Group,NaN,NaN,NaN
19,GB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,(011223344)\n17 Zaba Tower\nLondon\nNN9 7FR\nGB,NaN,NaN,NaN,NaN,NaN,NaN

#Transform

We'll have a look at how the data look in a csv file and decide which columns are relevant to us while creating empty variables to begin with

In [63]:

product_category = None #column 2
customer = None #this is in column 3
po = None #this is in column 4
order_date = None #column 5
ean = None #column 6
buyer_code = None #column 7
deliver_to = None #column 12
delivery_date = None #column 13
item = None #column 14
cases = None #column 24
qty = None #column 26
unit_price = None #column 27
order_value = None #column 28

I'm getting rid of columns I know I won't use

In [64]:
orders = orders.drop(columns=[0,1,8,9,10,11,15,16,17,18,19,20,21,22,23,25])

In [65]:
for n, obj in enumerate(orders[2]):
        if type(orders.loc[n, 2]) == str:
            product_category = orders.loc[n, 2]
        else:
            orders.loc[n, 2] = product_category

In [66]:
for n, obj in enumerate(orders[3]):
        if type(orders.loc[n, 3]) == str:
            customer = orders.loc[n, 3]
        else:
            orders.loc[n, 3] = customer

In [67]:
for n, obj in enumerate(orders[4]):
  if type(orders.loc[n,4]) == str:
    po = orders.loc[n,4]
  else:
    orders.loc[n,4] = po

In [68]:
for n, obj in enumerate(orders[5]):
  if type(orders.loc[n,5]) == str:
    order_date = orders.loc[n,5]
  else:
    orders.loc[n,5] = order_date

In [69]:
for n, obj in enumerate(orders[6]):
        if type(orders.loc[n, 6]) == str:
            ean = orders.loc[n, 6]
        else:
            orders.loc[n, 6] = ean

In [70]:
for n, obj in enumerate(orders[7]):
        if type(orders.loc[n, 7]) == str:
            buyer_code = orders.loc[n, 7]
        else:
            orders.loc[n, 7] = buyer_code

In [71]:
for n, obj in enumerate(orders[12]):
        if type(orders.loc[n, 12]) == str:
            deliver_to = orders.loc[n, 12]
        else:
            orders.loc[n, 12] = deliver_to

In [72]:
for n, obj in enumerate(orders[13]):
        if type(orders.loc[n, 13]) == str:
            delivery_date = orders.loc[n, 13]
        else:
            orders.loc[n, 13] = delivery_date

In [73]:
for n, obj in enumerate(orders[14]):
        if type(orders.loc[n, 14]) == str:
            item = orders.loc[n, 14]
        else:
            orders.loc[n, 14] = item

In [74]:
for n, obj in enumerate(orders[24]):
        if type(orders.loc[n, 24]) == str:
            cases = orders.loc[n, 24]
        else:
            orders.loc[n, 24] = cases

In [75]:
for n, obj in enumerate(orders[26]):
        if type(orders.loc[n, 26]) == str:
            qty = orders.loc[n, 26]
        else:
            orders.loc[n, 26] = qty

In [76]:
for n, obj in enumerate(orders[27]):
        if type(orders.loc[n, 27]) == str:
            unit_price = orders.loc[n, 27]
        else:
            orders.loc[n, 27] = unit_price

In [77]:
for n, obj in enumerate(orders[28]):
        if type(orders.loc[n, 28]) == str:
            order_value = orders.loc[n, 28]
        else:
            orders.loc[n, 28] = order_value

In [78]:
orders.head(20)

/usr/local/lib/python3.12/dist-packages/google/colab/_dataframe_summarizer.py:88: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  cast_date_col = pd.to_datetime(column, errors="coerce")

,2,3,4,5,6,7,12,13,14,24,26,27,28
0,None,DESIGNER LIVING CO,None,None,None,None,Modern Furniture Co,None,None,None,None,None,None
1,None,DESIGNER LIVING CO,None,None,None,None,Modern Furniture Co,None,None,None,None,None,None
2,None,DESIGNER LIVING CO,None,None,None,None,Modern Furniture Co,None,None,None,None,None,None
3,None,DESIGNER LIVING CO,None,None,None,None,Modern Furniture Co,None,None,None,None,None,None
4,None,DESIGNER LIVING CO,None,None,None,None,Modern Furniture Co,None,None,None,None,None,None
5,None,DESIGNER LIVING CO,None,None,None,None,Modern Furniture Co,None,None,None,None,None,None
6,None,DESIGNER LIVING CO,None,None,None,None,Modern Furniture Co,None,None,None,None,None,None
7,None,DESIGNER LIVING CO,None,None,None,None,Modern Furniture Co,None,None,None,None,None,None
8,None,DESIGNER LIVING CO,0050920111,None,None,None,Modern Furniture Co,None,None,None,None,None,None
9,None,DESIGNER LIVING CO,0050920111,17/08/2023,None,None,Modern Furniture Co,18/08/2023 at 00:00,None,None,None,None,None
10,None,DESIGNER LIVING CO,0050920111,17/08/2023,None,None,Modern Furniture Co,18/08/2023 at 00:00,None,None,None,None,None
11,None,DESIGNER LIVING CO,0050920111,17/08/2023,None,None,Modern Furniture Co,18/08/2023 at 00:00,None,None,None,None,None
12,None,DESIGNER LIVING CO,0050920111,17/08/2023,None,None,Modern Furniture Co,18/08/2023 at 00:00,None,None,None,None,None
13,None,DESIGNER LIVING CO,0050920111,17/08/2023,None,None,Modern Furniture Co,18/08/2023 at 00:00,None,None,None,None,None
14,Seller Code,DESIGNER LIVING CO,0050920111,17/08/2023,Barcode,Buyer Code,Modern Furniture Co,18/08/2023 at 00:00,Description,Packing,Quantity,Unit Price,Value
15,OAKWOOD DINIG TABLE,DESIGNER LIVING CO,0050920111,17/08/2023,1012223334445,012345678,Modern Furniture Co,18/08/2023 at 00:00,Oakwood FURNITURE ITEMS\nProductType: FURNITUR...,1,2.,120.00,240.00
16,OAKWOOD DINIG TABLE,DESIGNER LIVING CO,0050920111,17/08/2023,1012223334445,012345678,Modern Furniture Co,18/08/2023 at 00:00,Oakwood FURNITURE ITEMS\nProductType: FURNITUR...,Total Qty:,2,Total Value:,240.00
17,OAKWOOD DINIG TABLE,DESIGNER LIVING CO,0050920111,17/08/2023,1012223334445,012345678,Modern Furniture Co,18/08/2023 at 00:00,Oakwood FURNITURE ITEMS\nProductType: FURNITUR...,Total Qty:,2,Total Value:,240.00
18,OAKWOOD DINIG TABLE,DESIGNER LIVING CO,0050920111,17/08/2023,1012223334445,012345678,Modern Furniture Co 7452,18/08/2023 at 00:00,Oakwood FURNITURE ITEMS\nProductType: FURNITUR...,Total Qty:,2,Total Value:,240.00
19,OAKWOOD DINIG TABLE,DESIGNER LIVING CO,0050920111,17/08/2023,1012223334445,012345678,Modern Furniture Co 7452,18/08/2023 at 00:00,Oakwood FURNITURE ITEMS\nProductType: FURNITUR...,Total Qty:,2,Total Value:,240.00

I'm now ready to rename my columns and get rid of rows that I don't need

In [79]:
orders.columns = ['product_category', 'customer', 'po', 'order_date', 'ean', 'buyer_code', 'deliver_to', 'delivery_date', 'item', 'cases', 'qty', 'unit_price', 'order_value']

In [83]:
orders = orders.dropna()

In [85]:
orders['deliver_to'].unique()

array(['Modern Furniture Co', 'Modern Furniture Co 7452',
       'Modern Furniture Co 7461', 'Modern Furniture Co 7439',
       'Modern Furniture Co 7445', 'WAL-MART DC 7457',
       'Modern Furniture Co 7460', 'Modern Warehouse 1',
       'Modern Warehouse 2', 'Modern Warehouse 3', 'Modern Warehouse 4',
       'Modern Warehouse 5', 'Modern Warehouse 6', 'Modern Warehouse 7',
       'Modern Warehouse 8', 'Modern Warehouse 9', 'Modern Warehouse 10',
       'Modern Warehouse 11', 'Elegant Warehouse 1',
       'Elegant Warehouse 2', 'Elegant Warehouse 3',
       'Elegant Warehouse 4', 'Elegant Warehouse 5',
       'Elegant Warehouse 6', 'Elegant Warehouse 7',
       'Elegant Warehouse 8', 'Elegant Warehouse 9',
       'Elegant Warehouse 10', 'Elegant Warehouse 11',
       'Elegant Warehouse 12'], dtype=object)

In [86]:
orders = orders[orders['product_category'] != 'Seller Code']
orders = orders[orders['ean'] != 'Barcode']
orders = orders[orders['buyer_code'] != 'Buyer Code']
orders = orders[orders['item'] != 'Description']
orders = orders[orders['cases'] != 'Packing']
orders = orders[orders['cases'] != 'Total Qty:']
orders = orders[orders['qty'] != 'Quantity']
orders = orders[orders['unit_price'] != 'Unit Price']
orders = orders[orders['unit_price'] != 'Total Value:']
orders = orders[orders['order_value'] != 'Value']

In [87]:
orders.head(20)

,product_category,customer,po,order_date,ean,buyer_code,deliver_to,delivery_date,item,cases,qty,unit_price,order_value
15,OAKWOOD DINIG TABLE,DESIGNER LIVING CO,0050920111,17/08/2023,1012223334445,012345678,Modern Furniture Co,18/08/2023 at 00:00,Oakwood FURNITURE ITEMS\nProductType: FURNITUR...,1,2.,120.00,240.00
33,OAKWOOD DINIG TABLE,DESIGNER LIVING CO,0123911680,17/08/2023,1012223334445,012345678,Modern Furniture Co 7452,18/08/2023 at 00:00,Oakwood FURNITURE ITEMS\nProductType: FURNITUR...,2,4.,120.00,480.00
50,OAKWOOD DINIG TABLE,DESIGNER LIVING CO,1234902716,17/08/2023,1012223334445,012345678,Modern Furniture Co 7461,18/08/2023 at 00:00,Oakwood FURNITURE ITEMS\nProductType: FURNITUR...,1,2.,120.00,240.00
67,OAKWOOD DINIG TABLE,DESIGNER LIVING CO,1234902713,17/08/2023,1012223334445,012345678,Modern Furniture Co 7439,18/08/2023 at 00:00,Oakwood FURNITURE ITEMS\nProductType: FURNITUR...,2,4.,120.00,480.00
86,OAKWOOD DINIG TABLE,DESIGNER LIVING CO,1234910986,17/08/2023,1012223334445,012345678,Modern Furniture Co 7445,18/08/2023 at 16:00,Oakwood FURNITURE ITEMS\nProductType: FURNITUR...,4,8.,120.00,960.00
103,OAKWOOD DINIG TABLE,DESIGNER LIVING CO,1234577855,17/08/2023,1012223334445,012345678,WAL-MART DC 7457,18/08/2023 at 00:00,Oakwood FURNITURE ITEMS\nProductType: FURNITUR...,4,8.,120.00,960.00
121,OAKWOOD DINIG TABLE,DESIGNER LIVING CO,1230886825,17/08/2023,1012223334445,012345678,Modern Furniture Co 7460,18/08/2023 at 00:00,Oakwood FURNITURE ITEMS\nProductType: FURNITUR...,1,2.,120.00,240.00
139,OAKWOOD DINIG TABLE,DESIGNER LIVING CO,8750861234,17/08/2023,1012223334445,012345678,Modern Furniture Co 7460,18/08/2023 at 00:00,Oakwood FURNITURE ITEMS\nProductType: FURNITUR...,5,10.,120.00,1200.00
156,OAKWOOD DINIG TABLE,DESIGNER LIVING CO,9350891234,17/08/2023,1012223334445,012345678,Modern Furniture Co 7460,18/08/2023 at 00:00,Oakwood FURNITURE ITEMS\nProductType: FURNITUR...,1,2.,120.00,240.00
352,FURN VASE,ELEGANT FURNISHING,XX09229047123,17/08/2023,02060084123456,1236888,Elegant Warehouse 1,18/08/2023,Vases FURNITURE ITEMS 1kg\nProductType: FURNIT...,8,70.,36.96,2587.20
367,FURN VASE,ELEGANT FURNISHING,XX66251428123,17/08/2023,02060084123456,1236888,Elegant Warehouse 2,18/08/2023,Vases FURNITURE ITEMS 1kg\nProductType: FURNIT...,8,70.,36.96,2587.20
382,FURN VASE SMALL,ELEGANT FURNISHING,XX09509114123,17/08/2023,5000084456123,111222333,Elegant Warehouse 3,19/08/2023,Small items\nProductType: FURNITURE ITEMS\nWar...,8,10.,7.44,74.40
397,FURN VASE SMALL,ELEGANT FURNISHING,XX11567662001 T,17/08/2023,5000084456123,111222333,Elegant Warehouse 4,19/08/2023,Small items\nProductType: FURNITURE ITEMS\nWar...,8,9.,7.44,66.96
411,FURN VASE SMALL,ELEGANT FURNISHING,XX13525555123,17/08/2023,5000084456123,111222333,Elegant Warehouse 5,19/08/2023,Small items\nProductType: FURNITURE ITEMS\nWar...,8,5.,7.44,37.20
426,FURN VASE SMALL,ELEGANT FURNISHING,XX17544667123,17/08/2023,5000084456123,111222333,Elegant Warehouse 6,19/08/2023,Small items\nProductType: FURNITURE ITEMS\nWar...,8,12.,7.44,89.28
441,FURN VASE SMALL,ELEGANT FURNISHING,XX19511622123,17/08/2023,5000084456123,111222333,Elegant Warehouse 7,19/08/2023,Small items\nProductType: FURNITURE ITEMS\nWar...,8,9.,7.44,66.96
457,FURN VASE SMALL,ELEGANT FURNISHING,XX23584451001 T,17/08/2023,5000084456123,111222333,Elegant Warehouse 8,19/08/2023,Small items\nProductType: FURNITURE ITEMS\nWar...,8,8.,7.44,59.52
471,FURN VASE SMALL,ELEGANT FURNISHING,XX31555713123,17/08/2023,5000084456123,111222333,Elegant Warehouse 9,19/08/2023,Small items\nProductType: FURNITURE ITEMS\nWar...,8,16.,7.44,119.04
485,FURN VASE SMALL,ELEGANT FURNISHING,XX50570872123,17/08/2023,5000084456123,111222333,Elegant Warehouse 10,19/08/2023,Small items\nProductType: FURNITURE ITEMS\nWar...,8,4.,7.44,29.76
499,FURN VASE SMALL,ELEGANT FURNISHING,XX84550904123,17/08/2023,5000084456123,111222333,Elegant Warehouse 11,19/08/2023,Small items\nProductType: FURNITURE ITEMS\nWar...,8,9.,7.44,66.96

In [89]:
orders.sample(1)

,product_category,customer,po,order_date,ean,buyer_code,deliver_to,delivery_date,item,cases,qty,unit_price,order_value
382,FURN VASE SMALL,ELEGANT FURNISHING,XX09509114123,17/08/2023,5000084456123,111222333,Elegant Warehouse 3,19/08/2023,Small items\nProductType: FURNITURE ITEMS\nWar...,8,10.,7.44,74.40

In [90]:
orders = orders[['order_date', 'po', 'customer', 'buyer_code', 'product_category', 'item', 'ean', 'delivery_date', 'deliver_to', 'cases', 'qty', 'unit_price', 'order_value']]

#Load

In [92]:
file_name = 'orders_adj.xlsx'
orders.to_excel(file_name)